name: publish

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      run: cargo login ${{ secrets.CRATES_TOKEN }}
    - name: Publish
      run: cargo publish
